 version: '2'
 services:
   proxy:
     image: $REPO/opendcp/proxy:$VER
     depends_on:
        - hubble
        - web
     volumes:
        - ./conf/proxy_www.conf:/etc/php5/fpm/pool.d/www.conf:rw
        - ./conf/rsyncd.conf:/etc/rsyncd.conf
        - ./logs:/data1/logs:rw
        - ./data/Runtime:/data1/hubble/Runtime:rw
     volumes_from:
        - hubble
        - web
     ports:
        - "5555:5555"
        - "8889:8889"
        - "8888:8888"
        - "8080:8080"
        - "873:873"
   web:
     image: $REPO/opendcp/ui:$VER
     volumes:
        - ./conf/web.conf:/etc/nginx/conf.d/web.conf:rw
        - ./conf/web_conf.php:/data1/web/include/config.inc.php
   orion:
     image: $REPO/opendcp/orion:$VER
     volumes:
        - ./wait-for-it.sh:/wait-for-it.sh
        - ./conf/orion.conf:/go/src/weibo.com/opendcp/orion/conf/app.conf
        - ./logs/:/go/src/weibo.com/opendcp/orion/logs/
     ports:
        - "8081:8080"
     depends_on:
        - octans
        - jupiter
        - db_init
     entrypoint: /wait-for-it.sh db_init:11111 -t 25 -- ./run.sh
   octans:
     image: $REPO/opendcp/octans:$VER
     volumes:
        - ./wait-for-it.sh:/wait-for-it.sh
        - ./conf/octans.yml:/data/octans/config.yml
        - ./conf/octans_roles:/data/octans/ansible/roles
        - ./logs/:/data/octans/log/
     ports:
        - "8082:8000"
     depends_on:
        - db_init
     entrypoint: /wait-for-it.sh db_init:11111 -t 25 -- ./run.sh
   jupiter:
     image: $REPO/opendcp/jupiter:$VER
     volumes:
        - ./wait-for-it.sh:/wait-for-it.sh
        - ./conf/jupiter.json:/go/src/weibo.com/opendcp/jupiter/conf/jupiter.json
        - ./conf/jupiter.conf:/go/src/weibo.com/opendcp/jupiter/conf/app.conf
        - ./logs:/go/src/weibo.com/opendcp/jupiter/logs
     ports:
        - "8083:8080"
     depends_on:
       - db_init
     entrypoint: /wait-for-it.sh db_init:11111 -t 25 -- ./run.sh
   hubble:
     image: $REPO/opendcp/hubble:$VER
     volumes:
        - ./conf/hubble_nginx.conf:/etc/nginx/conf.d/hubble.conf:rw
        - ./conf/hubble_conf.php:/data1/hubble/Application/Common/Conf/config.php:rw
   imagebuild:
     image: $REPO/opendcp/imagebuild:$VER
     privileged: true
     volumes:
        - ./logs/imagebuild:/tmp
        - ./data/project:/imagebuild/$VER
     ports:
        - "8084:8080"
     environment:
        - SERVER_IP=host_ip
        - SERVER_PORT=8084
        - MYSQL_HOST=db
        - MYSQL_PORT=3306
        - MYSQL_USER=root
        - MYSQL_PASSWORD=12345
        - PLUGIN_VIEW_URL=/api/for_repos/proxy_view_plugin.php
        - EXTENSION_INTERFACE_URL=/api/for_repos/proxy_interface.php
        - HARBOR_ADDRESS=harbor_ip:12380
        - HARBOR_USER=admin
        - HARBOR_PASSWORD=Harbor12345
        - CLUSTERLIST_ADDRESS=orion:8080
   db_init:
     image: $REPO/opendcp/db_init:$VER
     environment:
       - MYSQL_ROOT_PASSWORD=12345
       - DB_HOST=db
       - INIT_PORT=11111
     volumes:
       - ./wait-for-it.sh:/wait-for-it.sh
     depends_on:
       - db
     entrypoint: /wait-for-it.sh db:3306 -t 40 -- ./run.sh
   db:
     image: registry.cn-beijing.aliyuncs.com/opendcp/mysql:latest
     volumes:
       #- ./logs/mysql/:/var/log/mysql/
       - ./conf/my.cnf:/etc/mysql/my.cnf
       - ./data/mysql-data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=12345
     ports:
       - "3306:3306"
